Another tweak to prevent Copyright entries matching 2021-2021.

diff --git a/environment/git/pre-commit-copyright b/environment/git/pre-commit-copyright
--- a/environment/git/pre-commit-copyright
+++ b/environment/git/pre-commit-copyright
@@ -75,18 +75,21 @@ function rewrite_copyright_block()
   debugprint "$create_date $git_last_mod_date $git_create_date"
 
   # Sanity Checks
-  [[ "${create_date}" =~ "Copyright" ]] && die "Failed to parse copyright line (err 1)"
-  # [[ "${mod_date}" =~ "Copyright" ]] && die "Failed to parse copyright line"
-  [[ "${git_last_mod_date}" =~ "Copyright" ]] && die "Failed to parse copyright line (err 2)"
-  [[ "${git_create_date}" =~ "Copyright" ]] && die "Failed to parse copyright line (err 3)"
+  [[ "${create_date}" =~ "Copyright" ]] && echo "Failed to parse copyright line (err 1)" && exit 1
+  # [[ "${mod_date}" =~ "Copyright" ]] && echo "Failed to parse copyright line" && exit 1
+  [[ "${git_last_mod_date}" =~ "Copyright" ]] && echo "Failed to parse copyright line (err 2)" &&
+    exit 1
+  [[ "${git_create_date}" =~ "Copyright" ]] && echo "Failed to parse copyright line (err 3)" &&
+    exit 1
+
   if [[ "${create_date}" -gt "${today}" ]] || [[ "${create_date}" -lt "1990" ]]; then
-    die "Existing copyright date range is corrupt. Please fix $filename manually."
+    echo "Existing copyright date range is corrupt. Please fix $filename manually." && exit 1
   fi
   if [[ "${git_create_date}" -gt "${today}" ]] || [[ "${git_create_date}" -lt "1990" ]]; then
-    die "Existing copyright date range is corrupt. Please fix $filename manually."
+    echo "Existing copyright date range is corrupt. Please fix $filename manually." && exit 1
   fi
   if [[ "${create_date}" -gt "${today}" ]] || [[ "${create_date}" -lt "1990" ]]; then
-    die "Existing copyright date range is corrupt. Please fix $filename manually."
+    echo "Existing copyright date range is corrupt. Please fix $filename manually." && exit 1
   fi
 
   # We converted from CVS to svn in 2010. This is the oldest create date that git will report.  In
@@ -94,9 +97,11 @@ function rewrite_copyright_block()
   [[ "${git_create_date}" -lt "2011" ]] && git_create_date="${create_date}"
 
   # Expected Copyright line:
-  local ecrl="Copyright (C) ${git_create_date}-${today} Triad National Security, LLC., "
-  ecrl+="All rights reserved."
-  debugprint "ecrl = $ecrl"
+  local ecrl="Copyright (C) "
+  if [[ "${git_create_date}" != "${today}" ]]; then
+    ecrl+="${git_create_date}-"
+  fi
+  ecrl+="${today} Triad National Security, LLC., All rights reserved."
 
   # If existing copyright spans two lines, reduce it to one line.
   local twolines
@@ -126,7 +131,7 @@ suffix="$(date +%s)"
 
 # clean up any older fprettify patches
 # $DELETE_OLD_PATCHES && rm -f /tmp/$USER/$prefix-*. &> /dev/null
-mkdir -p "/tmp/$USER" || die "Could not create /tmp/$USER"
+mkdir -p "/tmp/$USER" || ( echo "Could not create /tmp/$USER" && exit 1 )
 patchfile=$(mktemp "/tmp/$USER/${prefix}-${suffix}.patch.XXXXXXXX")
 
 # create one patch containing all changes to the files
